trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - master
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS

jobs:
  - template: azure/coverage_job.yml
    parameters:
      configurationName: COVERAGE_DEBUG_ZTS
      configurationParameters: '--enable-debug --disable-maintainer-zts'
