trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - master

jobs:
  - template: azure/job.yml
    parameters:
      configurationName: DEBUG_NTS
      configurationParameters: >-
          --enable-debug --disable-zts
          CFLAGS='-fsanitize=undefined,address -DZEND_TRACK_ARENA_ALLOC'
          LDFLAGS='-fsanitize=undefined,address'
      runTestsParameters: --asan
      timeoutInMinutes: 120
  - template: azure/job.yml
    parameters:
      configurationName: DEBUG_ZTS
      configurationParameters: >-
          --enable-debug --enable-zts
          CFLAGS='-fsanitize=undefined,address -DZEND_TRACK_ARENA_ALLOC'
          LDFLAGS='-fsanitize=undefined,address'
      runTestsParameters: --asan
      timeoutInMinutes: 120
  - template: azure/job.yml
    parameters:
      configurationName: RELEASE_NTS
      configurationParameters: >-
          --disable-debug --disable-zts
          CFLAGS='-fsanitize=undefined,address -DZEND_TRACK_ARENA_ALLOC'
          LDFLAGS='-fsanitize=undefined,address'
      runTestsParameters: --asan
      timeoutInMinutes: 120
  - template: azure/job.yml
    parameters:
      configurationName: RELEASE_ZTS
      configurationParameters: >-
          --disable-debug --enable-zts
          CFLAGS='-fsanitize=undefined,address -DZEND_TRACK_ARENA_ALLOC'
          LDFLAGS='-fsanitize=undefined,address'
      runTestsParameters: --asan
      timeoutInMinutes: 120
